### ISSUE TITLE
macOS warning about case sensitivity and ARCHITECTURE.md and architecture.md

### ISSUE THREAD

**Issue by simonw** [bpcreech/PyMiniRacer#1]
### Steps to reproduce

On macOS, run this:
```bash
git clone https://github.com/bpcreech/PyMiniRacer
```

### Actual behavior

You get these warnings:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/ARCHITECTURE.md'
  'docs/architecture.md'
  'docs/CONTRIBUTING.md'
  'docs/contributing.md'
```

**Comment by simonw** [comment]
Here's the problem:

https://github.com/bpcreech/PyMiniRacer/tree/main/docs

![CleanShot 2024-03-23 at 18 16 27@2x](https://github.com/bpcreech/PyMiniRacer/assets/9599/f263f4b6-ae99-4f31-93e0-7a1f23e77c14)

I suggest dropping the lowercase ones.

**Comment by bpcreech** [comment]
Thanks for the report! My daily driver is Ubuntu, so any Mac testing is done via GitHub Actions or vicariously.
