### ISSUE TITLE
Does this use the v8 sandbox?

### ISSUE THREAD

**Issue by simonw** [bpcreech/PyMiniRacer#25]
I just read this: https://v8.dev/blog/sandbox

Does the build of V8 used by PyMiniRacer use this V8 feature? I think it's a compile-time option.

**Comment by bpcreech** [comment]
Good question (meaning "I had to check")! Yes, it is enabled on all platforms we build official wheels for, and [here's a test asserting so](https://github.com/bpcreech/PyMiniRacer/pull/31/checks) which will go into the next release.

**Comment by simonw** [comment]
Thanks!
